[tool.poetry]
name = "vidmergebot"
version = "1.5.3"
description = ""
authors = ["Divanshu Chauhan <divkix@divkix.me>"]

[tool.poetry.dependencies]
python = "^3.9"
asyncio = "^3.4.3"
Pyrogram = "^2.0.100"
TgCrypto = "^1.2.5"
aiodns = "^3.0.0"
aiohttp = "^3.8.4"
hachoir = "^3.2.0"
humanfriendly = "^10.0"
Pillow = "^9.4.0"
cachetools = "^5.3.0"
pymongo = "^4.3.3"
dnspython = "^2.3.0"
aiofiles = "^23.1.0"
prettyconf = "^2.2.1"
pyromod = "^2.0.0"

[tool.poetry.dev-dependencies]
black = "^23.1.0"
pylint = "^2.17.0"
pre-commit = "^3.1.0"
pyclean = "^2.7.0"
isort = "^5.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
